export const ADD_DATA_TO_COLLECTION = "ADD_DATA_TO_COLLECTION";
export const MAP_DATA_TO_SUPPLIERS_STATE = "MAP_DATA_TO_SUPPLIERS_STATE";
export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";
export const UNMOUNT_SUPPLIER = "UNMOUNT_SUPPLIER";
export const CHANGE_SUPPLIER_VID = "CHANGE_SUPPLIER_VID";
